### ISSUE TITLE
ArrayIndexOutOfBoundsException for MutableLongObjectMap.withoutAllKeys

### ISSUE THREAD

**Issue by aewhite** [goldmansachs/gs-collections#23]
I'm using version 6.1.0 when I ran across the following error:

```
java.lang.ArrayIndexOutOfBoundsException: 16
	at com.gs.collections.impl.map.mutable.primitive.LongObjectHashMap$KeysSetIterator.next(LongObjectHashMap.java:3725)
	at com.gs.collections.impl.iterator.UnmodifiableLongIterator.next(UnmodifiableLongIterator.java:42)
	at com.gs.collections.impl.lazy.primitive.SelectLongIterable$SelectLongIterator.hasNext(SelectLongIterable.java:233)
	at com.gs.collections.impl.map.mutable.primitive.LongObjectHashMap.withoutAllKeys(LongObjectHashMap.java:2574)
```

**Comment by aewhite** [comment]
I retract this bug report. I was using a lazy iterator over the keys to the map I was modifying.
