### ISSUE TITLE
ArrayIndexOutOfBoundsException while iterating over UnifiedMap

### ISSUE THREAD

**Issue by yeison** [goldmansachs/gs-collections#24]
I was iterating over a unifiedMap using values view and hit an ArrayIndexOutOfBoundsException

    for (Object o : unifiedMap.valuesView()) 

|

    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1048576
	    at com.gs.collections.impl.map.mutable.UnifiedMap$ValuesIterator.next(UnifiedMap.java:2564)
	    at com.gs.collections.impl.UnmodifiableIteratorAdapter.next(UnmodifiableIteratorAdapter.java:42)
	    at com.gs.futures.lexicon.product.client.components.InstrumentCache.unionOfChildMapsAsInstrumentList(InstrumentCache.java:471)

**Comment by yeison** [comment]
If I just use values() instead of valuesView I don't hit the error

**Comment by motlin** [comment]
Do you mutate the UnifiedMap inside the loop? Do you have any additional information that would help reproduce the exception?

**Comment by yeison** [comment]
Perhaps I am mutating my map somewhere else concurrently.  When I add a lock the issue goes away and I can still use valuesView().  I'll close this ticket and continue to look into it.  If I can reproduce it with the lock I'll let you know.
